# Statistical Exploration

## Libraries
```{r message=FALSE, warning=FALSE}
library(lme4)
```

## Declare variables
```{r variables}
# data
article <- text1 %>% select(-c(nfix, refix))

# dependent variable
duration = article$dur
log_duration = log(duration)

# independent variable
valency = article$AAPz

# confounders
# lexical-level 
word_length = article$word_length
word_frequency = article$frequency
#predictability = TBD
POS = article$pos

# participant-level
participant = article$participant_id
```


## Correlation
```{r correlation}
duration[is.na(duration)] <- 0

cor(word_length,duration)
cor(word_frequency, duration)
cor(valency, duration)
```
```{r}
cor_by_participant <- tapply(word_length, participant, function(word_length_subset) {
  duration_subset <- duration[participant == levels(participant)[length(word_length_subset)]]
  cor(word_length_subset, duration_subset)})

print(cor_by_participant)
```


### Log-Transformation
Note: Values that are *NA* must be dealt with. There are multiple options for handling missing values. 
While they could be removed, this would lead to a loss of data.  
Another approach is to set it to a very low value, for example 1ms.
```{r}
hist(duration)
hist(log_duration)
```

## Regression
```{r}
lm(duration ~ valency)
```


```{r log_transform}
# Replace Inf and -Inf values with 0
log_duration[is.infinite(log_duration)] <- 0

result <- lm(log_duration ~ valency)
summary(result)
```

```{r}
result <- lmer(log_duration ~ valency + (1 + valency | word_length))
summary(result)
```


```{r}
result <- lmer(duration ~ valency + (1 + valency | participant) + (1 + valency | word_length))
summary(result)
```



